                                             <option>select</option>
                                                <option value='Afghanistan'>Afghanistan (؋)</option>
                                                <option value='Albania'>Albania (Lek)</option>
                                                <option value='Algeria'>Algeria (دج)</option>
                                                <option value='American Samoa'>American Samoa ($)</option>
                                                <option value='Andorra'>Andorra (€)</option>
                                                <option value='Angola'>Angola (Kz)</option>
                                                <option value='Anguilla'>Anguilla ($)</option>
                                                <option value='Antarctica'>Antarctica ($)</option>
                                                <option value='Antigua and Barbuda'>Antigua and Barbuda ($)</option>
                                                <option value='Argentina'>Argentina ($)</option>
                                                <option value='Armenia'>Armenia (֏)</option>
                                                <option value='Aruba'>Aruba (ƒ)</option>
                                                <option value='Australia'>Australia ($)</option>
                                                <option value='Austria'>Austria (€)</option>
                                                <option value='Azerbaijan'>Azerbaijan (AZN)</option>
                                                <option value='Bahamas'>Bahamas ($)</option>
                                                <option value='Bahrain'>Bahrain (د.)</option>
                                                <option value='Bangladesh'>Bangladesh (ó)</option>
                                                <option value='Barbados'>Barbados ($)</option>
                                                <option value='Belarus'>Belarus (Br)</option>
                                                <option value='Belgium'>Belgium (€)</option>
                                                <option value='Belize'>Belize ($)</option>
                                                <option value='Benin'>Benin (CFA)</option>
                                                <option value='Bermuda'>Bermuda ($)</option>
                                                <option value='Bhutan'>Bhutan (Nu)</option>
                                                <option value='Bolivia'>Bolivia (Bs)</option>
                                                <option value='Bosnia and Herzegovina'>Bosnia and Herzegovina (KM)</option>
                                                <option value='Botswana'>Botswana (P)</option>
                                                <option value='Bouvet Island'>Bouvet Island (kr)</option>
                                                <option value='Brazil'>Brazil (R$)</option>
                                                <option value='British Indian Ocean Territory'>British Indian Ocean Territory ($)</option>
                                                <option value='Brunei Darussalam'>Brunei Darussalam (B$)</option>
                                                <option value='Bulgaria'>Bulgaria (Лв.)</option>
                                                <option value='Burkina Faso'>Burkina Faso (CFA)</option>
                                                <option value='Burundi'>Burundi (FBu)</option>
                                                <option value='Cambodia'>Cambodia (៛)</option>
                                                <option value='Cameroon'>Cameroon (FCFA)</option>
                                                <option value='Canada'>Canada ($)</option>
                                                <option value='Cape Verde'>Cape Verde ($)</option>
                                                <option value='Cayman Islands'>Cayman Islands ($)</option>
                                                <option value='Central African Republic'>Central African Republic (FCFA)</option>
                                                <option value='Chad'>Chad (FCFA)</option>
                                                <option value='Chile'>Chile ($)</option>
                                                <option value='China'>China (¥)</option>
                                                <option value='Christmas Island'>Christmas Island ($)</option>
                                                <option value='Cocos (Keeling) Islands'>Cocos (Keeling) Islands ($)</option>
                                                <option value='Colombia'>Colombia ($)</option>
                                                <option value='Comoros'>Comoros (CF)</option>
                                                <option value='Congo'>Congo (FC)</option>
                                                <option value='Democratic Republic of the Congo'>Democratic Republic of the Congo (FC)</option>
                                                <option value='Cook Islands'>Cook Islands ($)</option>
                                                <option value='Costa Rica'>Costa Rica (₡)</option>
                                                <option value="Cote D'Ivoire">Cote D'Ivoire (CFA)</option>
                                                <option value='Croatia'>Croatia (Kn)</option>
                                                <option value='Cuba'>Cuba ($)</option>
                                                <option value='Cyprus'>Cyprus (€)</option>
                                                <option value='Czech Republic'>Czech Republic (Kč)</option>
                                                <option value='Denmark'>Denmark (kr)</option>
                                                <option value='Djibouti'>Djibouti (Fdj)</option>
                                                <option value='Dominica'>Dominica ($)</option>
                                                <option value='Dominican Republic'>Dominican Republic (RD$)</option>
                                                <option value='Ecuador'>Ecuador (S/.)</option>
                                                <option value='Egypt'>Egypt (E£)</option>
                                                <option value='El Salvador'>El Salvador (₡)</option>
                                                <option value='Equatorial Guinea'>Equatorial Guinea (FCFA)</option>
                                                <option value='Eritrea'>Eritrea (Nkf)</option>
                                                <option value='Estonia'>Estonia (kr)</option>
                                                <option value='Ethiopia'>Ethiopia (Br)</option>
                                                <option value='Falkland Islands (Malvinas)'>Falkland Islands (Malvinas) (£)</option>
                                                <option value='Faroe Islands'>Faroe Islands (kr)</option>
                                                <option value='Fiji'>Fiji (FJ$)</option>
                                                <option value='Finland'>Finland (mk)</option>
                                                <option value='France'>France (€)</option>
                                                <option value='French Guiana'>French Guiana (€)</option>
                                                <option value='French Polynesia'>French Polynesia (F)</option>
                                                <option value='French Southern Territories'>French Southern Territories (€)</option>
                                                <option value='Gabon'>Gabon (FCFA)</option>
                                                <option value='Gambia'>Gambia (D)</option>
                                                <option value='Georgia'>Georgia (GEL)</option>
                                                <option value='Germany'>Germany (€)</option>
                                                <option value='Ghana'>Ghana (GH₵)</option>
                                                <option value='Gibraltar'>Gibraltar (£)</option>
                                                <option value='Greece'>Greece (€)</option>
                                                <option value='Greenland'>Greenland (Kr.)</option>
                                                <option value='Grenada'>Grenada ($)</option>
                                                <option value='Guadeloupe'>Guadeloupe (€)</option>
                                                <option value='Guam'>Guam ($)</option>
                                                <option value='Guatemala'>Guatemala (Q)</option>
                                                <option value='Guernsey'>Guernsey (£)</option>
                                                <option value='Guinea'>Guinea (FG)</option>
                                                <option value='Guinea-Bissau'>Guinea-Bissau (CFA)</option>
                                                <option value='Guyana'>Guyana (G$)</option>
                                                <option value='Haiti'>Haiti (G)</option>
                                                <option value='Heard Island and McDonald Islands'>Heard Island and McDonald Islands ($)</option>
                                                <option value='Holy See (Vatican City State)'>Holy See (Vatican City State) (₤)</option>
                                                <option value='Honduras'>Honduras (HNL)</option>
                                                <option value='Hong Kong'>Hong Kong (HK$)</option>
                                                <option value='Hungary'>Hungary (Ft)</option>
                                                <option value='Iceland'>Iceland (kr)</option>
                                                <option value='India'>India (₹)</option>
                                                <option value='Indonesia'>Indonesia (Rp)</option>
                                                <option value='Islamic Republic of Iran'>Islamic Republic of Iran (IRR)</option>
                                                <option value='Iraq'>Iraq (د.ع)</option>
                                                <option value='Ireland'>Ireland (€)</option>
                                                <option value='Isle of Man'>Isle of Man (£)</option>
                                                <option value='Israel'>Israel (₪)</option>
                                                <option value='Italy'>Italy (€)</option>
                                                <option value='Jamaica'>Jamaica (J$)</option>
                                                <option value='Japan'>Japan (¥)</option>
                                                <option value='Jersey'>Jersey (£)</option>
                                                <option value='Jordan'>Jordan (د.ا)</option>
                                                <option value='Kazakhstan'>Kazakhstan (₸)</option>
                                                <option value='Kenya'>Kenya (KSh)</option>
                                                <option value='Kiribati'>Kiribati ($)</option>
                                                <option value="Democratic People's Republic of Korea">Democratic People's Republic of Korea (₩)</option>
                                                <option value='Republic of Korea'>Republic of Korea (₩)</option>
                                                <option value='Kuwait'>Kuwait (د.ك)</option>
                                                <option value='Kyrgyzstan'>Kyrgyzstan (лв)</option>
                                                <option value="Lao People's Democratic Republic">Lao People's Democratic Republic (₭)</option>
                                                <option value='Latvia'>Latvia (LVL)</option>
                                                <option value='Lebanon'>Lebanon (ل.ل)</option>
                                                <option value='Lesotho'>Lesotho (L)</option>
                                                <option value='Liberia'>Liberia (L$)</option>
                                                <option value='Libyan Arab Jamahiriya'>Libyan Arab Jamahiriya (LD)</option>
                                                <option value='Liechtenstein'>Liechtenstein (CHF)</option>
                                                <option value='Lithuania'>Lithuania (Lt)</option>
                                                <option value='Luxembourg'>Luxembourg (€)</option>
                                                <option value='Macao'>Macao (MOP$)</option>
                                                <option value='The Former Yugoslav Republic of Macedonia'>The Former Yugoslav Republic of Macedonia (den)</option>
                                                <option value='Madagascar'>Madagascar (Ar)</option>
                                                <option value='Malawi'>Malawi (K)</option>
                                                <option value='Malaysia'>Malaysia (RM)</option>
                                                <option value='Maldives'>Maldives (Rf)</option>
                                                <option value='Mali'>Mali (MAF)</option>
                                                <option value='Malta'>Malta (€)</option>
                                                <option value='Marshall Islands'>Marshall Islands ($)</option>
                                                <option value='Martinique'>Martinique (€)</option>
                                                <option value='Mauritania'>Mauritania (MRU</option>
                                                <option value='Mauritius'>Mauritius (₨)</option>
                                                <option value='Mayotte'>Mayotte (€)</option>
                                                <option value='Mexico'>Mexico ($)</option>
                                                <option value='Federated States of Micronesia'>Federated States of Micronesia ($)</option>
                                                <option value='Republic of Moldova'>Republic of Moldova (L)</option>
                                                <option value='Monaco'>Monaco (€)</option>
                                                <option value='Mongolia'>Mongolia (₮)</option>
                                                <option value='Montenegro'>Montenegro (€)</option>
                                                <option value='Montserrat'>Montserrat ($)</option>
                                                <option value='Morocco'>Morocco (MAD)</option>
                                                <option value='Mozambique'>Mozambique (MT)</option>
                                                <option value='Myanmar'>Myanmar (K)</option>
                                                <option value='Namibia'>Namibia (N$)</option>
                                                <option value='Nauru'>Nauru ($)</option>
                                                <option value='Nepal'>Nepal (Rs)</option>
                                                <option value='Netherlands'>Netherlands (ANG)</option>
                                                <option value='Netherlands Antilles'>Netherlands Antilles (NAf)</option>
                                                <option value='New Caledonia'>New Caledonia (F)</option>
                                                <option value='New Zealand'>New Zealand ($)</option>
                                                <option value='Nicaragua'>Nicaragua (C$)</option>
                                                <option value='Niger'>Niger (XOF)</option>
                                                <option value='Nigeria'>Nigeria (₦)</option>
                                                <option value='Niue'>Niue ($)</option>
                                                <option value='Norfolk Island'>Norfolk Island ($)</option>
                                                <option value='Northern Mariana Islands'>Northern Mariana Islands ($)</option>
                                                <option value='Norway'>Norway (kr)</option>
                                                <option value='Oman'>Oman (ر.ع.)</option>
                                                <option value='Pakistan'>Pakistan (₨)</option>
                                                <option value='Palau'>Palau ($)</option>
                                                <option value='Occupied Palestinian Territory'>Occupied Palestinian Territory ($)</option>
                                                <option value='Panama'>Panama (B/)</option>
                                                <option value='Papua New Guinea'>Papua New Guinea (K)</option>
                                                <option value='Paraguay'>Paraguay (₲)</option>
                                                <option value='Peru'>Peru (S/)</option>
                                                <option value='Philippines'>Philippines (₱)</option>
                                                <option value='Pitcairn'>Pitcairn ($)</option>
                                                <option value='Poland'>Poland (zł)</option>
                                                <option value='Portugal'>Portugal (€)</option>
                                                <option value='Puerto Rico'>Puerto Rico ($)</option>
                                                <option value='Qatar'>Qatar (QR)</option>
                                                <option value='Reunion'>Reunion (€)</option>
                                                <option value='Romania'>Romania (lei)</option>
                                                <option value='Russian Federation'>Russian Federation (₽)</option>
                                                <option value='Rwanda'>Rwanda (FRw)</option>
                                                <option value='Saint Barthélemy'>Saint Barthélemy (€)</option>
                                                <option value='Saint Helena'>Saint Helena (£)</option>
                                                <option value='Saint Kitts and Nevis'>Saint Kitts and Nevis ($)</option>
                                                <option value='Saint Lucia'>Saint Lucia ($)</option>
                                                <option value='Saint Martin'>Saint Martin (ƒ)</option>
                                                <option value='Saint Pierre and Miquelon'>Saint Pierre and Miquelon (€)</option>
                                                <option value='Saint Vincent and the Grenadines'>Saint Vincent and the Grenadines (X$)</option>
                                                <option value='Samoa'>Samoa ($)</option>
                                                <option value='San Marino'>San Marino (€)</option>
                                                <option value='Sao Tome and Principe'>Sao Tome and Principe (Db)</option>
                                                <option value='Saudi Arabia'>Saudi Arabia (﷼)</option>
                                                <option value='Senegal'>Senegal (CFA)</option>
                                                <option value='Serbia'>Serbia (din)</option>
                                                <option value='Seychelles'>Seychelles (SCR)</option>
                                                <option value='Sierra Leone'>Sierra Leone (Le)</option>
                                                <option value='Singapore'>Singapore (S$)</option>
                                                <option value='Slovakia'>Slovakia (SKK)</option>
                                                <option value='Slovenia'>Slovenia (€)</option>
                                                <option value='Solomon Islands'>Solomon Islands (Si$)</option>
                                                <option value='Somalia'>Somalia (Sh.so.)</option>
                                                <option value='South Africa'>South Africa (R)</option>
                                                <option value='South Georgia and the South Sandwich Islands'>South Georgia and the South Sandwich Islands (£)</option>
                                                <option value='Spain'>Spain (€)</option>
                                                <option value='Sri Lanka'>Sri Lanka (Rs)</option>
                                                <option value='Sudan'>Sudan (£SD)</option>
                                                <option value='Suriname'>Suriname ($)</option>
                                                <option value='Svalbard and Jan Mayen'>Svalbard and Jan Mayen (kr)</option>
                                                <option value='Swaziland'>Swaziland (L)</option>
                                                <option value='Sweden'>Sweden (kr)</option>
                                                <option value='Switzerland'>Switzerland (CHf)</option>
                                                <option value='Syrian Arab Republic'>Syrian Arab Republic (LS)</option>
                                                <option value='Taiwan, Province Of China'>Taiwan, Province Of China (NT$)</option>
                                                <option value='Tajikistan'>Tajikistan (SM)</option>
                                                <option value='United Republic of Tanzania'>United Republic of Tanzania (TSh)</option>
                                                <option value='Thailand'>Thailand (฿))</option>
                                                <option value='Timor-Leste'>Timor-Leste ($)</option>
                                                <option value='Togo'>Togo (CFA)</option>
                                                <option value='Tokelau'>Tokelau ($)</option>
                                                <option value='Tonga'>Tonga (T$)</option>
                                                <option value='Trinidad and Tobago'>Trinidad and Tobago (TT$)</option>
                                                <option value='Tunisia'>Tunisia (د.ت)</option>
                                                <option value='Turkey'>Turkey (₺)</option>
                                                <option value='Turkmenistan'>Turkmenistan (T)</option>
                                                <option value='Turks and Caicos Islands'>Turks and Caicos Islands ($)</option>
                                                <option value='Tuvalu'>Tuvalu ($)</option>
                                                <option value='Uganda'>Uganda (USh)</option>
                                                <option value='Ukraine'>Ukraine (₴)</option>
                                                <option value='United Arab Emirates'>United Arab Emirates (د.إ)</option>
                                                <option value='United Kingdom'>United Kingdom (£)</option>
                                                <option value='United States'>United States ($)</option>
                                                <option value='United States Minor Outlying Islands'>United States Minor Outlying Islands ($)</option>
                                                <option value='Uruguay'>Uruguay ($)</option>
                                                <option value='Uzbekistan'>Uzbekistan (лв)</option>
                                                <option value='Vanuatu'>Vanuatu (VT)</option>
                                                <option value='Venezuela'>Venezuela (Bs.)</option>
                                                <option value='Vietnam'>Vietnam (₫)</option>
                                                <option value='British, Virgin Islands'>British, Virgin Islands ($)</option>
                                                <option value='U.S., Virgin Islands'>U.S., Virgin Islands ($)</option>
                                                <option value='Wallis And Futuna'>Wallis And Futuna (Fr)</option>
                                                <option value='Western Sahara'>Western Sahara (د.م.)</option>
                                                <option value='Yemen'>Yemen (﷼)</option>
                                                <option value='Zambia'>Zambia (ZK)</option>
                                                <option value='Zimbabwe'>Zimbabwe (Z$)</option>
